version: '3'
services:
    python-bot:
        build: .
        container_name: memebot
        networks:
            - python-bot
    mongodb:
        image: mongo:latest
        container_name: mongodb_memebot
        networks:
            - python-bot
networks:
    python-bot: